# примеры API-запросов

@baseUrl = http://localhost:8000/api

###

# получение датчиков
GET {{baseUrl}}/sensors/details/1/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/create/
Content-Type: application/json

{
  "sensor_name": "ESP32_2",
  "description": "Датчик в комнате"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/change/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 28.1
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json